### ISSUE TITLE
How to create a model file? 

### ISSUE THREAD

**Issue by goenyan** [TareHimself/osu-ai#1]
Hello, 
I want to ask how I can create a model? I tried "Collect data'' option, it show "Ready to capture frames" but I don't understand what its trying to capture. I tried in-game footage but it didn't work, or did it just capture the replay video with .mp4 extension?
Thank you.

**Comment by TareHimself** [comment]
Right now the process assumes that your setup is the same as mine, I want to make it somewhat dynamic then I will post steps to collect data, train and test here

**Comment by TareHimself** [comment]
Ok I added more info to the readme, data is captured from the game and the process is controlled by python. clone the required repositories from the readme, run main.py, select collect data, name the project then press the `\` key to start collecting data. It won't screenshot anything unless you are in a map. At that point just go to osu, enable autoplay, open a map, and wait for it to end. then press `\` again and then press ctrl-c. It will compress the data and store it. Then you can train a model on that data

**Comment by goenyan** [comment]
Thank you very much.
May I have your Discord?
P/S: My monitor is running in 2K res, do I need to set it back to 1080p?

**Comment by TareHimself** [comment]
Tare#3664

**Comment by goenyan** [comment]
> Tare#3664

Thank you.
I've sent a friend request.

**Comment by DODOPC** [comment]
My danser-0.11.0-win cannot replay the record file .json
